name = "cravio-r2-upload"
main = "src/index.ts"
compatibility_date = "2024-12-01"

account_id = "26dc307587c029d1917fdfd5f929e6e9"
workers_dev = true

[vars]
PUBLIC_BASE_URL = "https://cravio-r2-upload.zulfiqarammar8.workers.dev"

[[r2_buckets]]
binding = "BUCKET"
bucket_name = "craviobucket"

[env.production]
workers_dev = false

# Secrets:
# wrangler secret put API_KEY
# wrangler secret put WORKER_UPLOAD_ALLOWED_ORIGIN (optional)
